# This file is generated by .github/scripts/generate_formula.py in
# HernandoR/zerobrew and overwritten on every release. Edit it there.
class Zerobrew < Formula
  desc "Package manager alternative to Homebrew, in Rust"
  homepage "https://github.com/HernandoR/zerobrew"
  version "0.3.3"
  license all_of: ["Apache-2.0", "MIT"]

  # Linux uses the statically linked musl build, so there is no glibc
  # floor and the same binary runs in minimal containers and Colab.

  on_macos do
    on_arm do
      url "https://github.com/HernandoR/zerobrew/releases/download/v0.3.3/zb-darwin-arm64"
      sha256 "33bd331135d7c8817db4de0192a937f07b71fc470c67b733fc89c71517933d0f"

      resource "zbx" do
        url "https://github.com/HernandoR/zerobrew/releases/download/v0.3.3/zbx-darwin-arm64"
        sha256 "082a03eb4b7e5d6c8afef92af9e3914b2a34e1552e1120ae622768a36024702b"
      end
    end
    on_intel do
      url "https://github.com/HernandoR/zerobrew/releases/download/v0.3.3/zb-darwin-x64"
      sha256 "8b71fd70a59345ec6426a04a22ac66ed52d9b4ada272334632c2f91d8ba09027"

      resource "zbx" do
        url "https://github.com/HernandoR/zerobrew/releases/download/v0.3.3/zbx-darwin-x64"
        sha256 "f2d51ed8967c9e8c2da67b3a92da802d66e5e5c1797fa361f37814bda8a91395"
      end
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/HernandoR/zerobrew/releases/download/v0.3.3/zb-linux-arm64-musl"
      sha256 "93d0eba9e1f10025b382994362511c4a2020d7a417fe4fe76d62ccd93d611d96"

      resource "zbx" do
        url "https://github.com/HernandoR/zerobrew/releases/download/v0.3.3/zbx-linux-arm64-musl"
        sha256 "b0eafba5af49eca9fe4011c06c3ed2e8f29e768da400e0a6b066c3272b1a7aef"
      end
    end
    on_intel do
      url "https://github.com/HernandoR/zerobrew/releases/download/v0.3.3/zb-linux-x64-musl"
      sha256 "e1fd22eac0ff238af28fd18ea4dedf4df33fe865da05cccb8701b99457c10d59"

      resource "zbx" do
        url "https://github.com/HernandoR/zerobrew/releases/download/v0.3.3/zbx-linux-x64-musl"
        sha256 "97fc6aaacac7d9cb60a2c85bd39950a2fddb6754c18ce8943fd1330ea1fe5da7"
      end
    end
  end

  def install
    # Matched by glob rather than rebuilt from OS/arch, so that the
    # musl and glibc asset names are both handled without branching.
    zb = Dir["zb-*"].first
    odie "no zb binary in the download" if zb.nil?
    bin.install zb => "zb"

    # zbx locates zb as a sibling of its own executable, so both have to
    # land in the same bin directory.
    resource("zbx").stage do
      zbx = Dir["zbx-*"].first
      odie "no zbx binary in the download" if zbx.nil?
      bin.install zbx => "zbx"
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/zb --version")
    assert_match "zbx <formula>", shell_output("#{bin}/zbx 2>&1", 1)
  end
end
